/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Kompanija;
import domen.Korisnik;
import domen.Zaposleni;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import kons.Konstante;
import modeli.ModelTabeleZaposleni;
import transferObjekat.KlijentskiZahtev;

/**
 *
 * @author Gogic
 */
public class GlavnaKlijentskaForma extends javax.swing.JFrame {
    Korisnik korisnik;
    /**
     * Creates new form GlavnaKlijentskaForma
     */
    public GlavnaKlijentskaForma() {
        initComponents();
    }

    public GlavnaKlijentskaForma(Korisnik korisnik) throws HeadlessException {
        this.korisnik = korisnik;
        initComponents();
        srediKombo();
        srediTabelu();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbnGrupa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtMaticniBroj = new javax.swing.JTextField();
        txtDatumEvidencije = new javax.swing.JTextField();
        cmbTipKompanija = new javax.swing.JComboBox();
        rbnDa = new javax.swing.JRadioButton();
        rbnNe = new javax.swing.JRadioButton();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaposleni = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klijent forma");

        jLabel1.setText("Naziv kompanije:");

        jLabel2.setText("Tip kompanije:");

        jLabel3.setText("PDV obveznik:");

        jLabel4.setText("Maticni broj:");

        jLabel5.setText("Datum evidencije:");

        cmbTipKompanija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rbnGrupa.add(rbnDa);
        rbnDa.setSelected(true);
        rbnDa.setText("Da");

        rbnGrupa.add(rbnNe);
        rbnNe.setText("Ne");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblZaposleni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZaposleni);

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDatumEvidencije))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv)
                            .addComponent(cmbTipKompanija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbnDa)
                                .addGap(26, 26, 26)
                                .addComponent(rbnNe)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtMaticniBroj)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSacuvaj)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addGap(92, 92, 92)
                                .addComponent(btnObrisi)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipKompanija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbnDa)
                    .addComponent(rbnNe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDatumEvidencije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
       
            if(txtNaziv.getText().isEmpty() || txtMaticniBroj.getText().isEmpty() /*|| txtDatumEvidencije.getText().isEmpty()*/){
                JOptionPane.showMessageDialog(this, "Prvo popunite podatke kompanije");
                return;
            }
            //SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            //Date datum = sdf.parse(txtDatumEvidencije.getText());
            String maticni = txtMaticniBroj.getText();
            KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.VRATI_MATICNI, maticni);
            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
            
            boolean signal = (boolean) KomunikacijaSaServerom.getInstance().primiOdgovor().getOdgovor();
            if(!signal){
                JOptionPane.showMessageDialog(this, "Maticni broj vec postoji");
                return;
            }
            
            
            
            Kompanija komp = new Kompanija(0l, txtNaziv.getText(), (String) cmbTipKompanija.getSelectedItem(), rbnDa.isSelected(), txtMaticniBroj.getText(), new Date(), 0, korisnik);
            txtDatumEvidencije.setEnabled(false);
            txtMaticniBroj.setEnabled(false);
            txtNaziv.setEnabled(false);
            cmbTipKompanija.setEnabled(false);
            rbnDa.setEnabled(false);
            rbnNe.setEnabled(false);
            
            Zaposleni z = new Zaposleni();
            z.setKompanija(komp);
            DodajZaposlenogForma dzf = new DodajZaposlenogForma(this, true, z);
            dzf.setVisible(true);
            
            ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
            mtz.dodajUTabelu(z);
            
            
            
            
        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
        mtz.obrisiIzTabele(tblZaposleni.getSelectedRow());
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
        ArrayList<Zaposleni> listaZap = mtz.getListaZap();
        if(listaZap.isEmpty()){
            JOptionPane.showMessageDialog(this, "Mora imati bar jednog zaposlenog");
            return;
        }
        int brojZap = listaZap.size();
        for (Zaposleni zaposleni : listaZap) {
            zaposleni.getKompanija().setBrojZaposlenih(brojZap);
        }
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.SACUVAJ_KOMPANIJU, listaZap);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
        
        boolean signal = false;
        signal = (boolean) KomunikacijaSaServerom.getInstance().primiOdgovor().getOdgovor();
        
        if(signal){
            JOptionPane.showMessageDialog(this, "Uspesno sacuvano");
            resetujFormu();
            mtz.resetuj();
            return;
        }else{
            JOptionPane.showMessageDialog(this, "NEUSPESNO sacuvano");
            resetujFormu();
            mtz.resetuj();
            return;
        }
        
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaKlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbTipKompanija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbnDa;
    private javax.swing.ButtonGroup rbnGrupa;
    private javax.swing.JRadioButton rbnNe;
    private javax.swing.JTable tblZaposleni;
    private javax.swing.JTextField txtDatumEvidencije;
    private javax.swing.JTextField txtMaticniBroj;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private void srediKombo() {
        cmbTipKompanija.removeAllItems();
        
        cmbTipKompanija.addItem("Akcionarsko drustvo");
        cmbTipKompanija.addItem("DOO");
        cmbTipKompanija.addItem("Ortacko drustvo");
        cmbTipKompanija.addItem("Komandno drustvo");
        cmbTipKompanija.addItem("Preduzetnik");
    }

    private void srediTabelu() {
        ModelTabeleZaposleni mtz = new ModelTabeleZaposleni();
        tblZaposleni.setModel(mtz);
    }

    private void resetujFormu() {
        txtDatumEvidencije.setEnabled(true);
            txtMaticniBroj.setEnabled(true);
            txtNaziv.setEnabled(true);
            cmbTipKompanija.setEnabled(true);
            rbnDa.setEnabled(true);
            rbnNe.setEnabled(true);
    }
}
