/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Meteorolog;
import domen.Prognoza;
import domen.PrognozaRegion;
import domen.Region;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kom.Komunikacija;
import kons.Konstante;
import modeli.ModelTabelePrognoza;
import transferObjekat.KlijentskiZahtev;

/**
 *
 * @author Gogic
 */
public class GlavnaKlijentskaForma extends javax.swing.JFrame {
    Meteorolog m;
    /**
     * Creates new form GlavnaKlijentskaForma
     */
    

    public GlavnaKlijentskaForma(Meteorolog m) throws HeadlessException {
        this.m = m;
        initComponents();
        srediCMB();
        podesiTabelu();
    }

    private GlavnaKlijentskaForma() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        txtDan = new javax.swing.JTextField();
        cmbRegion = new javax.swing.JComboBox();
        cmbMeteoAlarm = new javax.swing.JComboBox();
        cmbPojava = new javax.swing.JComboBox();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrognoza = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dan");

        jLabel2.setText("Opis");

        jLabel3.setText("Temperatura");

        jLabel4.setText("Region");

        jLabel5.setText("Meteo alarm");

        jLabel6.setText("Pojava");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        cmbRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbMeteoAlarm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPojava.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodaj.setText("Dodaj prognozu za region");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi prognozu za region");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblPrognoza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPrognoza);

        btnSacuvaj.setText("Sacuvaj prognozu za dan");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDan)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtTemperatura)
                                    .addComponent(cmbRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMeteoAlarm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbPojava, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnDodaj)
                                .addGap(31, 31, 31)
                                .addComponent(btnObrisi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(btnSacuvaj)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbMeteoAlarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPojava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
       
        ModelTabelePrognoza mtp = (ModelTabelePrognoza) tblPrognoza.getModel();
        
        ArrayList<PrognozaRegion> lista = mtp.getLista();
        PrognozaRegion pr = lista.get(tblPrognoza.getSelectedRow());
        cmbRegion.addItem(pr.getRegion());
        
       mtp.obrisiIzTabele(tblPrognoza.getSelectedRow());
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        String dan = txtDan.getText();
        String opis = txtOpis.getText();
        String temperatura = txtTemperatura.getText();
        if(cmbRegion.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Uneli ste sve regione");
            return;
        }
        
        if(dan.isEmpty() || opis.isEmpty() || temperatura.isEmpty()){
            JOptionPane.showMessageDialog(this, "Moraju biti popunjena sva polja");
            return;
        }
        
        double temp = Double.parseDouble(temperatura);
        if(temp < -50 || temp > 50){
            JOptionPane.showMessageDialog(this, "Temperatura mora biti od -50 do 50");
            return;
        }
       
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Prognoza p;
        try {
            p = new Prognoza(1, sdf.parse(dan), opis, m);
        } catch (ParseException ex) {
            System.out.println("Los datum");
            Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
        PrognozaRegion pr = new PrognozaRegion(p, 0, temp, (String) cmbMeteoAlarm.getSelectedItem(), (String) cmbPojava.getSelectedItem(), (Region)cmbRegion.getSelectedItem());
        
        ModelTabelePrognoza mtp = (ModelTabelePrognoza) tblPrognoza.getModel();
        mtp.dodajUTabelu(pr);
        
        txtDan.setEnabled(false);
        txtOpis.setEnabled(false);
        cmbRegion.removeItem(cmbRegion.getSelectedItem());
        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        if(cmbRegion.getSelectedItem() != null){
             JOptionPane.showMessageDialog(this, "Morate uneti prognozu za sve regione");
            return;
        }
        
        ModelTabelePrognoza mtp = (ModelTabelePrognoza) tblPrognoza.getModel();
        
        ArrayList<PrognozaRegion> listaPr = mtp.getLista();
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.SACUVAJ_PROGNOZU, listaPr);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        boolean signal = (boolean) Komunikacija.getInstance().primiOdgovor().getOdgovor();
        if(signal){
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana prognoza");
            mtp.resetuj();
            txtDan.setEnabled(true);
            txtOpis.setEnabled(true);
            srediCMB();
            return;
        }else{
            JOptionPane.showMessageDialog(this, "NIJE USPESNO SACUVANA PROGNOZA");
            mtp.resetuj();
            txtDan.setEnabled(true);
            txtOpis.setEnabled(true);
            srediCMB();
            return;
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaKlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbMeteoAlarm;
    private javax.swing.JComboBox cmbPojava;
    private javax.swing.JComboBox cmbRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPrognoza;
    private javax.swing.JTextField txtDan;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables

    private void srediCMB() {
        cmbMeteoAlarm.removeAllItems();
        cmbPojava.removeAllItems();
        cmbRegion.removeAllItems();
        
        cmbMeteoAlarm.addItem("Zeleni");
        cmbMeteoAlarm.addItem("Zuti");
        cmbMeteoAlarm.addItem("Narandzasti");
        cmbMeteoAlarm.addItem("Crveni");
        
        cmbPojava.addItem("Nema");
        cmbPojava.addItem("Vetar");
        cmbPojava.addItem("Kisa");
        cmbPojava.addItem("Sneg i Led");
        cmbPojava.addItem("Grmljavina");
        cmbPojava.addItem("Magla");
        cmbPojava.addItem("Sumski pozar");
        cmbPojava.addItem("Ekstremno visoke temperature");
        cmbPojava.addItem("Ekstremno niske temperature");
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.VRATI_REGIONE, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ArrayList<Region> listaR = (ArrayList<Region>) Komunikacija.getInstance().primiOdgovor().getOdgovor();
        
        for (Region region : listaR) {
            cmbRegion.addItem(region);
        }
    }

    private void podesiTabelu() {
        ModelTabelePrognoza mtp = new ModelTabelePrognoza();
        tblPrognoza.setModel(mtp);
    }
}
