/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Gazdinstvo;
import domen.Poljoprivrednik;
import domen.Stado;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import konstante.Konstante;
import modeli.ModelTabeleGazdinstva;
import transferObjekat.KlijentskiZahtev;

/**
 *
 * @author Gogic
 */
public class GlavnaKlijentskaForma extends javax.swing.JFrame {
    Poljoprivrednik poljoprivrednik;
    Gazdinstvo g;
    /**
     * Creates new form GlavnaKlijentskaForma
     */
    public GlavnaKlijentskaForma() {
        initComponents();
        srediTabelu();
         txtUkupnoSubvencija.setEnabled(false);
    }

    public GlavnaKlijentskaForma(Poljoprivrednik poljoprivrednik) throws HeadlessException {
        this.poljoprivrednik = poljoprivrednik;
        initComponents();
        txtUkupnoSubvencija.setEnabled(false);
        srediTabelu();
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKreirajGazdinstvo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        txtUkupnoSubvencija = new javax.swing.JTextField();
        btnDodajStado = new javax.swing.JButton();
        btnObrisiStado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGazdinstvo = new javax.swing.JTable();
        btnSacuvajGazdinstvo = new javax.swing.JButton();
        lblGazdinstvoID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKreirajGazdinstvo.setText("Kreiraj gazdinstvo");
        btnKreirajGazdinstvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajGazdinstvoActionPerformed(evt);
            }
        });

        jLabel1.setText("GazdinstvoID:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Datum registracije:");

        jLabel4.setText("Ukupno subvencija: ");

        btnDodajStado.setText("Dodaj stado");
        btnDodajStado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStadoActionPerformed(evt);
            }
        });

        btnObrisiStado.setText("Obrisi stado");
        btnObrisiStado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStadoActionPerformed(evt);
            }
        });

        tblGazdinstvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGazdinstvo);

        btnSacuvajGazdinstvo.setText("Sacuvaj gazdinstvo");
        btnSacuvajGazdinstvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajGazdinstvoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodajStado)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiStado))
                            .addComponent(btnKreirajGazdinstvo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)
                                .addComponent(lblGazdinstvoID))
                            .addComponent(btnSacuvajGazdinstvo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv)
                            .addComponent(txtDatum)
                            .addComponent(txtUkupnoSubvencija))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnKreirajGazdinstvo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblGazdinstvoID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUkupnoSubvencija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStado)
                    .addComponent(btnObrisiStado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajGazdinstvo)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajGazdinstvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajGazdinstvoActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.VRATI_MAX_ID, null);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
        
        int id = (int) KomunikacijaSaServerom.getInstance().primiOdgovor().getOdgovor();
       
        lblGazdinstvoID.setText(String.valueOf(id));
        
        g = new Gazdinstvo();
        g.setGazdinstvoID(id);
        kz.setOperacija(Konstante.NAPRAVI_GAZDINSTVO);
        kz.setParametar(g);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
        
        boolean signal = (boolean) KomunikacijaSaServerom.getInstance().primiOdgovor().getOdgovor();
        if(signal){
            JOptionPane.showMessageDialog(this, "Uspesno kreirano");
        }else{
            JOptionPane.showMessageDialog(this, "Neuspesno kreirano");
            return;
        }
        
        
    }//GEN-LAST:event_btnKreirajGazdinstvoActionPerformed

    private void btnDodajStadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStadoActionPerformed
        ModelTabeleGazdinstva mtg = (ModelTabeleGazdinstva) tblGazdinstvo.getModel();
        ArrayList <Stado> listaS = mtg.getListaStada();
        int id = 0;
        for (Stado stado : listaS) {
            if(stado.getStadoID() > id){
                id = stado.getStadoID() + 1;
            }
        }
        Stado s = new Stado();
        s.setGazdinstvo(g);
        s.setStadoID(id);
        StadoForma sf = new StadoForma(this, true,s);
        sf.setVisible(true);
        for (Stado stado : listaS) {
            if(stado.getZivotinja().equals(s.getZivotinja())){
                JOptionPane.showMessageDialog(this, "Vec postoji ta zivotinja");
                return;
            }
        }
        mtg.dodajUlistu(s);
        txtUkupnoSubvencija.setText(String.valueOf(mtg.vratiUkupnuSubvenciju()));
    }//GEN-LAST:event_btnDodajStadoActionPerformed

    private void btnObrisiStadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStadoActionPerformed
        ModelTabeleGazdinstva mtg = (ModelTabeleGazdinstva) tblGazdinstvo.getModel();
        mtg.obrisiIzListe(tblGazdinstvo.getSelectedRow());
        txtUkupnoSubvencija.setText(String.valueOf(mtg.vratiUkupnuSubvenciju()));
    }//GEN-LAST:event_btnObrisiStadoActionPerformed

    private void btnSacuvajGazdinstvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajGazdinstvoActionPerformed
         ModelTabeleGazdinstva mtg = (ModelTabeleGazdinstva) tblGazdinstvo.getModel();
         ArrayList<Stado> listaStada = mtg.getListaStada();
         if(listaStada.isEmpty()){
             JOptionPane.showMessageDialog(this, "Mora imati bar jedno stado");
             return;
         }
         SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            g.setDatumRegistracije(sdf.parse(txtDatum.getText()));
        } catch (ParseException ex) {
            
            JOptionPane.showMessageDialog(this, "Nije uspeo datum");
            return;
            
        }
         g.setGazdinstvoID(Integer.parseInt(lblGazdinstvoID.getText()));
         g.setNaziv(txtNaziv.getText());
         g.setPoljoprivrednik(poljoprivrednik);
         g.setUkupnoSubvencija(Double.parseDouble(txtUkupnoSubvencija.getText()));
         
         for (Stado stado : listaStada) {
            stado.setGazdinstvo(g);
        }
         
         KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.UPDATE_GAZDINSTVO, g);
         KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
         boolean signal1 = (boolean) KomunikacijaSaServerom.getInstance().primiOdgovor().getOdgovor();
         if(signal1){
             JOptionPane.showMessageDialog(this, "Uspesno izmenjeno gazdinstvo");
         }else{
             JOptionPane.showMessageDialog(this, "NESUSPESNO IZMENJENO GAZDINSTVO");
         }
         
         KlijentskiZahtev kz1 = new KlijentskiZahtev(Konstante.SACUVAJ_STADA, listaStada);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz1);
        boolean signal3 = (boolean) KomunikacijaSaServerom.getInstance().primiOdgovor().getOdgovor();
        if(signal3){
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana stada");
            mtg.resetuj();
        }else{
            JOptionPane.showMessageDialog(this, "NEUSPESNO SACUVANA STADA");
            return;
        }
         
         
    }//GEN-LAST:event_btnSacuvajGazdinstvoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaKlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStado;
    private javax.swing.JButton btnKreirajGazdinstvo;
    private javax.swing.JButton btnObrisiStado;
    private javax.swing.JButton btnSacuvajGazdinstvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGazdinstvoID;
    private javax.swing.JTable tblGazdinstvo;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtUkupnoSubvencija;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleGazdinstva mtg = new ModelTabeleGazdinstva();
        tblGazdinstvo.setModel(mtg);
    }

    public Gazdinstvo getG() {
        return g;
    }

   
    
}
