/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Nastavnik;
import domen.PredajePredmet;
import domen.Predmet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kom.Komunikacija;
import kons.Konstante;
import transferObjekat.KlijentskiZahtev;

/**
 *
 * @author Gogic
 */
public class DodajForma extends javax.swing.JDialog {
    PredajePredmet pp;
    /**
     * Creates new form DodajForma
     */
    public DodajForma(java.awt.Frame parent, boolean modal, PredajePredmet pp) {
        super(parent, modal);
        this.pp = pp;
        initComponents();
        srediSmerove();
        srediNastavnike();
        srediPredmete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbNastavnik = new javax.swing.JComboBox();
        cmbPredmet = new javax.swing.JComboBox();
        cmbSmer = new javax.swing.JComboBox();
        txtSemestar = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nastavnik");

        jLabel2.setText("Predmet");

        jLabel3.setText("Smer");

        jLabel4.setText("Semestar");

        cmbNastavnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPredmet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSmer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNastavnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPredmet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSmer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSemestar))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(btnDodaj)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbNastavnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbSmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSemestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnDodaj)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if(txtSemestar.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "popunite sva polja");
            return;
        }
        
        int semestar = Integer.parseInt(txtSemestar.getText());
        if(semestar > 8 || semestar < 1){
            JOptionPane.showMessageDialog(this, "semestar mora biti izmedju 1 i 8");
            return;
        }
        
        pp.setNastavnik((Nastavnik) cmbNastavnik.getSelectedItem());
        pp.setPredmet((Predmet) cmbPredmet.getSelectedItem());
        pp.setStudijskiProgram((String) cmbSmer.getSelectedItem());
        pp.setSemestar(semestar);
        
        this.dispose();
        
    }//GEN-LAST:event_btnDodajActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JComboBox cmbNastavnik;
    private javax.swing.JComboBox cmbPredmet;
    private javax.swing.JComboBox cmbSmer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtSemestar;
    // End of variables declaration//GEN-END:variables

    private void srediSmerove() {
        cmbSmer.removeAllItems();
        cmbSmer.addItem("ISIT");
        cmbSmer.addItem("MEN");
        cmbSmer.addItem("OM");
        cmbSmer.addItem("UK");
    }

    private void srediNastavnike() {
        cmbNastavnik.removeAllItems();
        KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.VRATI_NASTAVNIKE, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ArrayList<Nastavnik> lista = (ArrayList<Nastavnik>) Komunikacija.getInstance().primiOdgovor().getOdgovor();
        for (Nastavnik nastavnik : lista) {
            cmbNastavnik.addItem(nastavnik);
        }
    }

    private void srediPredmete() {
        cmbPredmet.removeAllItems();
        KlijentskiZahtev kz = new KlijentskiZahtev(Konstante.VRATI_PREDMETE, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ArrayList<Predmet> lista = (ArrayList<Predmet>) Komunikacija.getInstance().primiOdgovor().getOdgovor();
        for (Predmet nastavnik : lista) {
            cmbPredmet.addItem(nastavnik);
        }
    }
}
