/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Intervju;
import domen.Kandidat;
import domen.Regruter;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import kontroler.Kontroler;
import modeli.ModelTabeleRegruter;
import niti.OsveziNit;
import niti.PokreniServerNit;
import pomoc.PomocnaKlasa;

/**
 *
 * @author Gogic
 */
public class GlavnaServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaServerskaForma
     */
    public GlavnaServerskaForma() {
        initComponents();
        this.setLocationRelativeTo(null);
        PokreniServerNit psn = new PokreniServerNit();
        psn.start();
        srediTabelu();
        OsveziNit on = new OsveziNit(this);
        on.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegruteri = new javax.swing.JTable();
        chkOD = new javax.swing.JCheckBox();
        chkDO = new javax.swing.JCheckBox();
        txtDatumOd = new javax.swing.JTextField();
        txtDatumDo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server forma");

        tblRegruteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegruteri);

        chkOD.setText("Datum od:");

        chkDO.setText("Datum do:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkDO)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumDo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkOD)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumOd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkOD)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDO)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkDO;
    private javax.swing.JCheckBox chkOD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegruteri;
    private javax.swing.JTextField txtDatumDo;
    private javax.swing.JTextField txtDatumOd;
    // End of variables declaration//GEN-END:variables

    public void srediTabelu() {
        ModelTabeleRegruter mtr = new ModelTabeleRegruter();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        tblRegruteri.setModel(mtr);
       
        ArrayList<Regruter> listaRegruter = Kontroler.getInstance().vratiRegrutere();
        ArrayList<PomocnaKlasa> listaPom = new ArrayList<>();
        java.util.Date datumU1;
        try {
            datumU1 = sdf.parse("1.1.2070");
        
        Date datum1 = new Date(datumU1.getTime());
        java.util.Date datumU2 = sdf.parse("5.5.1970");
        Date datum2 = new Date(datumU2.getTime());
        if(chkDO.isSelected()){
                try {
                    datum1 = new Date(sdf.parse(txtDatumDo.getText()).getTime());
                    
                } catch (ParseException ex) {
                    System.out.println("Datum do nije lepo parsiran");
                    Logger.getLogger(GlavnaServerskaForma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        if(chkOD.isSelected()){
                try {
                    datum2 = new Date(sdf.parse(txtDatumOd.getText()).getTime());
                    
                } catch (ParseException ex) {
                  System.out.println("Datum do nije lepo parsiran");
                 Logger.getLogger(GlavnaServerskaForma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
        for (Regruter regruter : listaRegruter) {
            int id = regruter.getRegruterID();
            ArrayList<Kandidat> listaKandidata = Kontroler.getInstance().vratiKandidateDatum(id,datum1,datum2);
            PomocnaKlasa pk = new PomocnaKlasa(regruter, listaKandidata);
            listaPom.add(pk);
        }
        
        mtr.setListaPK(listaPom);
        
        } catch (ParseException ex) {
            Logger.getLogger(GlavnaServerskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
        
        
        
    }
}
